server:
  port: 4444

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yeni_verilenler_bazasi
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


